#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v16
# autospec commit: b858a2a
#
Name     : feh
Version  : 3.10.3
Release  : 20
URL      : https://feh.finalrewind.org/feh-3.10.3.tar.bz2
Source0  : https://feh.finalrewind.org/feh-3.10.3.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: feh-bin = %{version}-%{release}
Requires: feh-data = %{version}-%{release}
Requires: feh-license = %{version}-%{release}
Requires: feh-man = %{version}-%{release}
BuildRequires : curl-dev
BuildRequires : imlib2-dev
BuildRequires : libpng-dev
BuildRequires : perl(Test::Command)
BuildRequires : pkgconfig(xt)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Fix-prefix-location.patch

%description
# feh - Image Viewer and Cataloguer
**feh** is a light-weight, configurable and versatile image viewer.
It is aimed at command line users, but can also be started from graphical file
managers. Apart from viewing images, it can compile text and thumbnail
listings, show (un)loadable files, set X11 backgrounds, and more.

%package bin
Summary: bin components for the feh package.
Group: Binaries
Requires: feh-data = %{version}-%{release}
Requires: feh-license = %{version}-%{release}

%description bin
bin components for the feh package.


%package data
Summary: data components for the feh package.
Group: Data

%description data
data components for the feh package.


%package doc
Summary: doc components for the feh package.
Group: Documentation
Requires: feh-man = %{version}-%{release}

%description doc
doc components for the feh package.


%package license
Summary: license components for the feh package.
Group: Default

%description license
license components for the feh package.


%package man
Summary: man components for the feh package.
Group: Default

%description man
man components for the feh package.


%prep
%setup -q -n feh-3.10.3
cd %{_builddir}/feh-3.10.3
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1721239707
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
make  %{?_smp_mflags}  PREFIX=/usr


%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make test

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1721239707
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/feh
cp %{_builddir}/feh-%{version}/COPYING %{buildroot}/usr/share/package-licenses/feh/1444a07a3d4a7f6184613e75340401a136eb1d0b || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/feh

%files data
%defattr(-,root,root,-)
/usr/share/applications/feh.desktop
/usr/share/feh/fonts/black.style
/usr/share/feh/fonts/menu.style
/usr/share/feh/fonts/yudit.ttf
/usr/share/feh/images/feh.png
/usr/share/feh/images/feh.svg
/usr/share/feh/images/menubg_default.png
/usr/share/icons/hicolor/48x48/apps/feh.png
/usr/share/icons/hicolor/scalable/apps/feh.svg

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/feh/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/feh/1444a07a3d4a7f6184613e75340401a136eb1d0b

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/feh.1
