#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x100D5BFB5166E005 (derf@finalrewind.org)
#
Name     : feh
Version  : 2.28
Release  : 5
URL      : https://feh.finalrewind.org/feh-2.28.tar.bz2
Source0  : https://feh.finalrewind.org/feh-2.28.tar.bz2
Source99 : https://feh.finalrewind.org/feh-2.28.tar.bz2.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT-feh
Requires: feh-bin = %{version}-%{release}
Requires: feh-data = %{version}-%{release}
Requires: feh-license = %{version}-%{release}
Requires: feh-man = %{version}-%{release}
BuildRequires : curl-dev
BuildRequires : imlib2-dev
BuildRequires : libXinerama-dev
BuildRequires : libpng-dev
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xt)
Patch1: 0001-Fix-prefix-location.patch

%description
==============
This document was last updated on 20010223-1620-PST.
Please see the file COPYING for licensing information.

%package bin
Summary: bin components for the feh package.
Group: Binaries
Requires: feh-data = %{version}-%{release}
Requires: feh-license = %{version}-%{release}
Requires: feh-man = %{version}-%{release}

%description bin
bin components for the feh package.


%package data
Summary: data components for the feh package.
Group: Data

%description data
data components for the feh package.


%package doc
Summary: doc components for the feh package.
Group: Documentation
Requires: feh-man = %{version}-%{release}

%description doc
doc components for the feh package.


%package license
Summary: license components for the feh package.
Group: Default

%description license
license components for the feh package.


%package man
Summary: man components for the feh package.
Group: Default

%description man
man components for the feh package.


%prep
%setup -q -n feh-2.28
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1538146581
make  %{?_smp_mflags} PREFIX=/usr

%install
export SOURCE_DATE_EPOCH=1538146581
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/feh
cp COPYING %{buildroot}/usr/share/package-licenses/feh/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/feh

%files data
%defattr(-,root,root,-)
/usr/share/applications/feh.desktop
/usr/share/feh/fonts/black.style
/usr/share/feh/fonts/menu.style
/usr/share/feh/fonts/yudit.ttf
/usr/share/feh/images/feh.png
/usr/share/feh/images/feh.svg
/usr/share/feh/images/menubg_aluminium.png
/usr/share/feh/images/menubg_aqua.png
/usr/share/feh/images/menubg_black.png
/usr/share/feh/images/menubg_brushed.png
/usr/share/feh/images/menubg_default.png
/usr/share/feh/images/menubg_sky.png
/usr/share/icons/hicolor/48x48/apps/feh.png
/usr/share/icons/hicolor/scalable/apps/feh.svg

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/feh/*

%files license
%defattr(-,root,root,-)
/usr/share/package-licenses/feh/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/feh.1
